server:
    port: 5555

spring:
  application:
    name: gateway-service

eureka:
  instance:
    port: 8761
    ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:${eureka.instance.port}/eureka/

#zuul:
#  routes:
#    db-center-service:
#      path: /dbCenterService/**
#      stripPrefix: false
#    user-manager-service: /userManagerService/**
#ribbon:
#  eureka:
#    enabled: false #配置zuul路由时用将此属性设置为false

zuul:
  routes:
    user-manager-service:
      path: /userManagerService/**
#      stripPrefix: true
    db-center-service: /dbCenterService/**
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000

#  add-proxy-headers: true
#  max:
#    host:
#      connections: 500
#  host:
#    socket-timeout-millis: 60000
#    connect-timeout-millis: 60000

##超时相关设置
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 0
#  eureka:
#    enabled: true
